name: type-inference
version: 0.1.0.0
github: "ksrky/type-inference"
license: BSD3
author: "ksrk"
maintainer: "example@example.com"
copyright: "2022 ksrk"

language: Haskell2010
extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/type-inference#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - haskeline
  - mtl
  - prettyprinter
  - safe-exceptions
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  algorithmW:
    main: Main.hs
    source-dirs: src/algorithmW
  algorithmM:
    main: Main.hs
    source-dirs: src/algorithmM
  algorithmJ:
    main: Main.hs
    source-dirs: src/algorithmJ
  algorithmZ:
    main: Main.hs
    source-dirs: src/algorithmZ
  arbitrary-rank:
    main: Main.hs
    source-dirs: src/arbitrary-rank
  systemF:
    main: Main.hs
    source-dirs: src/systemF
  arbitrary-typed:
    main: Main.hs
    source-dirs: src/arbitrary-typed
